spring.application.name=ems-backend
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/ems_employees
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
#These two are used for server automatically changes the data
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
